# Generated by Django 5.0.3 on 2024-03-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoHabitaciones',
            fields=[
                ('id_tipo_hab', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Sencilla', 'Sencilla'), ('Doble', 'Doble'), ('Triple', 'Triple'), ('Suite', 'Suite')], default='Sencilla', max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('espacio', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('Id_habitacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=30)),
                ('id_tipo_hab', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Habitaciones.tipohabitaciones')),
            ],
        ),
    ]
