# Generated by Django 5.0.3 on 2024-03-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitaciones',
            name='id_tipo_hab',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
