# Generated by Django 5.0.3 on 2024-04-01 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Habitaciones', '0002_alter_tipohabitaciones_id_tipo_hab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaentrada', models.DateField()),
                ('fechasalida', models.DateField()),
                ('cantidad_Niños', models.IntegerField()),
                ('cantidad_Adultos', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Por Confirmar', 'Por Confirmar'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Por Confirmar', max_length=25)),
                ('Id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Habitaciones.habitaciones')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
